version: '2'

services:

  cclogger:
    build: .
    image: currentcostlogger
    container_name: cclogger
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - ./data:/root/data
    # Env vars are read from .env file automatically
    environment:
      IAM_NAME: ${IAM_NAME}
    restart: always
