version: '2'

services:

  cc_logger:
    build: .
    image: cc_logger
    container_name: cc_logger
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - ./data:/root/data
    restart: on-failure
